#!/bin/bash
vars=$(cat commands.config)
read NAME WDIR <<< $(echo ${vars} cat /usr/local/bin/commands.config | awk -F " " '{print $1" "$2}')

python /usr/local/bin/create_remote_repo.py $1
mkdir ${WDIR}/$1
cd ${WDIR}/$1
echo "# $1" >> README.md
touch .gitignore
git init
git add README.md
git commit -m "First commit"
git remote add origin git@github.com:${NAME}/$1.git
git push -u origin master
code .
